-- Add a unified, business-scoped document workflow for pre-sale, purchase,
-- dispatch, and invoice adjustment documents.
CREATE TABLE `business_documents` (
  `id` VARCHAR(191) NOT NULL,
  `businessId` VARCHAR(191) NOT NULL,
  `type` ENUM('QUOTATION', 'PROFORMA_INVOICE', 'PURCHASE_INVOICE', 'DELIVERY_CHALLAN', 'CREDIT_NOTE', 'DEBIT_NOTE') NOT NULL,
  `documentNumber` VARCHAR(191) NOT NULL,
  `status` ENUM('DRAFT', 'ISSUED', 'ACCEPTED', 'REJECTED', 'CONVERTED', 'CANCELLED') NOT NULL DEFAULT 'DRAFT',
  `customerId` VARCHAR(191) NULL,
  `supplierId` VARCHAR(191) NULL,
  `referenceInvoiceId` VARCHAR(191) NULL,
  `sourceDocumentId` VARCHAR(191) NULL,
  `convertedInvoiceId` VARCHAR(191) NULL,
  `issueDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `validUntil` DATETIME(3) NULL,
  `dueDate` DATETIME(3) NULL,
  `placeOfSupply` VARCHAR(191) NULL,
  `transportName` VARCHAR(191) NULL,
  `vehicleNumber` VARCHAR(191) NULL,
  `eWayBillNumber` VARCHAR(191) NULL,
  `referenceNumber` VARCHAR(191) NULL,
  `reason` TEXT NULL,
  `terms` TEXT NULL,
  `notes` TEXT NULL,
  `subTotal` DECIMAL(12, 2) NOT NULL,
  `taxTotal` DECIMAL(12, 2) NOT NULL,
  `discount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
  `grandTotal` DECIMAL(12, 2) NOT NULL,
  `stockAdjusted` BOOLEAN NOT NULL DEFAULT false,
  `createdById` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `deletedAt` DATETIME(3) NULL,

  UNIQUE INDEX `business_documents_businessId_documentNumber_key` (`businessId`, `documentNumber`),
  INDEX `business_documents_businessId_type_status_idx` (`businessId`, `type`, `status`),
  INDEX `business_documents_customerId_idx` (`customerId`),
  INDEX `business_documents_supplierId_idx` (`supplierId`),
  INDEX `business_documents_referenceInvoiceId_idx` (`referenceInvoiceId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `business_documents_businessId_fkey` FOREIGN KEY (`businessId`) REFERENCES `businesses` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `business_documents_customerId_fkey` FOREIGN KEY (`customerId`) REFERENCES `customers` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `business_documents_supplierId_fkey` FOREIGN KEY (`supplierId`) REFERENCES `suppliers` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `business_documents_referenceInvoiceId_fkey` FOREIGN KEY (`referenceInvoiceId`) REFERENCES `invoices` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `business_documents_sourceDocumentId_fkey` FOREIGN KEY (`sourceDocumentId`) REFERENCES `business_documents` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `business_documents_createdById_fkey` FOREIGN KEY (`createdById`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `business_document_items` (
  `id` VARCHAR(191) NOT NULL,
  `documentId` VARCHAR(191) NOT NULL,
  `itemId` VARCHAR(191) NULL,
  `description` VARCHAR(191) NOT NULL,
  `hsnSac` VARCHAR(191) NULL,
  `quantity` DECIMAL(12, 3) NOT NULL,
  `unit` VARCHAR(191) NOT NULL DEFAULT 'pcs',
  `unitPrice` DECIMAL(12, 2) NOT NULL,
  `taxRate` DECIMAL(5, 2) NOT NULL DEFAULT 0,
  `lineTotal` DECIMAL(12, 2) NOT NULL,

  INDEX `business_document_items_documentId_idx` (`documentId`),
  INDEX `business_document_items_itemId_idx` (`itemId`),
  PRIMARY KEY (`id`),
  CONSTRAINT `business_document_items_documentId_fkey` FOREIGN KEY (`documentId`) REFERENCES `business_documents` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `business_document_items_itemId_fkey` FOREIGN KEY (`itemId`) REFERENCES `items` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
