import type { PrintLanguage } from '../businesses/business-preferences.js';

export type PdfLabels = {
  taxInvoice: string;
  invoice: string;
  billedTo: string;
  billTo: string;
  supplier: string;
  issuedBy: string;
  invoiceDate: string;
  issueDate: string;
  validUntil: string;
  dueDate: string;
  againstInvoice: string;
  reference: string;
  placeOfSupply: string;
  transport: string;
  vehicleNumber: string;
  eWayBill: string;
  description: string;
  qty: string;
  rate: string;
  unitPrice: string;
  gst: string;
  tax: string;
  amount: string;
  hsnSac: string;
  subtotal: string;
  discount: string;
  total: string;
  paid: string;
  balanceDue: string;
  reason: string;
  terms: string;
  notes: string;
  gstin: string;
  tin: string;
  nonGst: string;
  signatory: string;
  billOfSupply: string;
  compositionNote: string;
  reverseCharge: string;
  yes: string;
  originalForRecipient: string;
  receivedBy: string;
  deliveredBy: string;
  acknowledgement: string;
  bankDetails: string;
  bankName: string;
  accountNumber: string;
  ifsc: string;
  upiId: string;
  scanToPay: string;
  paymentMode: string;
  totalQty: string;
  youSaved: string;
  roundOff: string;
  taxRoundOff: string;
  amountInWords: string;
  taxableAmount: string;
  cgst: string;
  sgst: string;
  igst: string;
  itemCode: string;
  received: string;
  partyBalance: string;
  documentTitles: Record<string, string>;
  thanks: (business: string) => string;
  computerGenerated: (title: string, business: string) => string;
};

const english: PdfLabels = {
  taxInvoice: 'TAX INVOICE',
  invoice: 'INVOICE',
  billedTo: 'Billed to',
  billTo: 'Bill to',
  supplier: 'Supplier',
  issuedBy: 'Issued by',
  invoiceDate: 'Invoice date',
  issueDate: 'Issue date',
  validUntil: 'Valid until',
  dueDate: 'Due date',
  againstInvoice: 'Against invoice',
  reference: 'Reference',
  placeOfSupply: 'Place of supply',
  transport: 'Transport',
  vehicleNumber: 'Vehicle number',
  eWayBill: 'E-way bill',
  description: 'Description',
  qty: 'Qty',
  rate: 'Rate',
  unitPrice: 'Unit price',
  gst: 'GST',
  tax: 'Tax',
  amount: 'Amount',
  hsnSac: 'HSN/SAC',
  subtotal: 'Subtotal',
  discount: 'Discount',
  total: 'Total',
  paid: 'Paid',
  balanceDue: 'Balance due',
  reason: 'Reason',
  terms: 'Terms &amp; conditions',
  notes: 'Notes',
  gstin: 'GSTIN',
  tin: 'TIN',
  nonGst: 'Non-GST business',
  signatory: 'Authorised signatory',
  billOfSupply: 'BILL OF SUPPLY',
  compositionNote: 'Composition taxable person, not eligible to collect tax on supplies',
  reverseCharge: 'Tax payable on reverse charge',
  yes: 'Yes',
  originalForRecipient: 'ORIGINAL FOR RECIPIENT',
  receivedBy: 'Received by',
  deliveredBy: 'Delivered by',
  acknowledgement: 'Received the above goods / services in good condition.',
  bankDetails: 'Bank details',
  bankName: 'Bank',
  accountNumber: 'Account no.',
  ifsc: 'IFSC',
  upiId: 'UPI ID',
  scanToPay: 'Scan to pay',
  paymentMode: 'Payment mode',
  totalQty: 'Total quantity',
  youSaved: 'You saved',
  roundOff: 'Round off',
  taxRoundOff: 'Tax round off',
  amountInWords: 'Amount in words',
  taxableAmount: 'Taxable amount',
  cgst: 'CGST',
  sgst: 'SGST',
  igst: 'IGST',
  itemCode: 'Item code',
  received: 'Received',
  partyBalance: 'Party\'s current balance',
  documentTitles: {
    QUOTATION: 'QUOTATION',
    PROFORMA_INVOICE: 'PROFORMA INVOICE',
    PURCHASE_INVOICE: 'PURCHASE INVOICE',
    DELIVERY_CHALLAN: 'DELIVERY CHALLAN',
    CREDIT_NOTE: 'CREDIT NOTE',
    DEBIT_NOTE: 'DEBIT NOTE',
  },
  thanks: (business) => `Thank you for your business &mdash; generated by ${business}`,
  computerGenerated: (title, business) => `This is a computer-generated ${title.toLowerCase()} from ${business}.`,
};

const hindi: PdfLabels = {
  taxInvoice: 'कर चालान',
  invoice: 'चालान',
  billedTo: 'बिल प्राप्तकर्ता',
  billTo: 'बिल प्राप्तकर्ता',
  supplier: 'आपूर्तिकर्ता',
  issuedBy: 'जारीकर्ता',
  invoiceDate: 'चालान तिथि',
  issueDate: 'जारी तिथि',
  validUntil: 'मान्य तिथि तक',
  dueDate: 'देय तिथि',
  againstInvoice: 'चालान के विरुद्ध',
  reference: 'संदर्भ',
  placeOfSupply: 'आपूर्ति का स्थान',
  transport: 'परिवहन',
  vehicleNumber: 'वाहन संख्या',
  eWayBill: 'ई-वे बिल',
  description: 'विवरण',
  qty: 'मात्रा',
  rate: 'दर',
  unitPrice: 'इकाई मूल्य',
  gst: 'जीएसटी',
  tax: 'कर',
  amount: 'राशि',
  hsnSac: 'एचएसएन/एसएसी',
  subtotal: 'उप-योग',
  discount: 'छूट',
  total: 'कुल',
  paid: 'भुगतान',
  balanceDue: 'शेष देय',
  reason: 'कारण',
  terms: 'नियम एवं शर्तें',
  notes: 'टिप्पणी',
  gstin: 'जीएसटीआईएन',
  tin: 'टिन',
  nonGst: 'गैर-जीएसटी व्यवसाय',
  signatory: 'अधिकृत हस्ताक्षरकर्ता',
  billOfSupply: 'आपूर्ति बिल',
  compositionNote: 'कंपोज़िशन कर-दाता, आपूर्ति पर कर वसूलने के पात्र नहीं',
  reverseCharge: 'रिवर्स चार्ज पर देय कर',
  yes: 'हाँ',
  originalForRecipient: 'प्राप्तकर्ता के लिए मूल प्रति',
  receivedBy: 'प्राप्तकर्ता',
  deliveredBy: 'पहुँचाने वाला',
  acknowledgement: 'उपरोक्त माल / सेवाएँ अच्छी स्थिति में प्राप्त हुईं।',
  bankDetails: 'बैंक विवरण',
  bankName: 'बैंक',
  accountNumber: 'खाता संख्या',
  ifsc: 'आईएफएससी',
  upiId: 'यूपीआई आईडी',
  scanToPay: 'भुगतान हेतु स्कैन करें',
  paymentMode: 'भुगतान का तरीका',
  totalQty: 'कुल मात्रा',
  youSaved: 'आपकी बचत',
  roundOff: 'राउंड ऑफ',
  taxRoundOff: 'कर राउंड ऑफ',
  amountInWords: 'राशि शब्दों में',
  taxableAmount: 'कर योग्य राशि',
  cgst: 'सीजीएसटी',
  sgst: 'एसजीएसटी',
  igst: 'आईजीएसटी',
  itemCode: 'वस्तु कोड',
  received: 'प्राप्त',
  partyBalance: 'पार्टी की वर्तमान शेष राशि',
  documentTitles: {
    QUOTATION: 'कोटेशन',
    PROFORMA_INVOICE: 'प्रोफ़ॉर्मा चालान',
    PURCHASE_INVOICE: 'खरीद चालान',
    DELIVERY_CHALLAN: 'डिलीवरी चालान',
    CREDIT_NOTE: 'क्रेडिट नोट',
    DEBIT_NOTE: 'डेबिट नोट',
  },
  thanks: (business) => `आपके व्यवसाय के लिए धन्यवाद &mdash; ${business}`,
  computerGenerated: (title, business) => `यह ${business} द्वारा कंप्यूटर से तैयार किया गया ${title} है।`,
};

const marathi: PdfLabels = {
  taxInvoice: 'कर बीजक',
  invoice: 'बीजक',
  billedTo: 'बिल प्राप्तकर्ता',
  billTo: 'बिल प्राप्तकर्ता',
  supplier: 'पुरवठादार',
  issuedBy: 'जारीकर्ता',
  invoiceDate: 'बीजक दिनांक',
  issueDate: 'जारी दिनांक',
  validUntil: 'वैधता दिनांक',
  dueDate: 'देय दिनांक',
  againstInvoice: 'बीजकाच्या विरोधात',
  reference: 'संदर्भ',
  placeOfSupply: 'पुरवठ्याचे ठिकाण',
  transport: 'वाहतूक',
  vehicleNumber: 'वाहन क्रमांक',
  eWayBill: 'ई-वे बिल',
  description: 'तपशील',
  qty: 'प्रमाण',
  rate: 'दर',
  unitPrice: 'एकक किंमत',
  gst: 'जीएसटी',
  tax: 'कर',
  amount: 'रक्कम',
  hsnSac: 'एचएसएन/एसएसी',
  subtotal: 'उप-एकूण',
  discount: 'सवलत',
  total: 'एकूण',
  paid: 'भरलेले',
  balanceDue: 'देय शिल्लक',
  reason: 'कारण',
  terms: 'अटी व शर्ती',
  notes: 'टीप',
  gstin: 'जीएसटीआयएन',
  tin: 'टिन',
  nonGst: 'जीएसटी नसलेला व्यवसाय',
  signatory: 'अधिकृत स्वाक्षरीकर्ता',
  billOfSupply: 'पुरवठा बिल',
  compositionNote: 'कंपोझिशन करदाता, पुरवठ्यावर कर आकारण्यास पात्र नाही',
  reverseCharge: 'रिव्हर्स चार्जवर देय कर',
  yes: 'होय',
  originalForRecipient: 'प्राप्तकर्त्यासाठी मूळ प्रत',
  receivedBy: 'स्वीकारणारा',
  deliveredBy: 'पोहोचवणारा',
  acknowledgement: 'वरील माल / सेवा चांगल्या स्थितीत मिळाल्या.',
  bankDetails: 'बँक तपशील',
  bankName: 'बँक',
  accountNumber: 'खाते क्रमांक',
  ifsc: 'आयएफएससी',
  upiId: 'यूपीआय आयडी',
  scanToPay: 'पैसे देण्यासाठी स्कॅन करा',
  paymentMode: 'पेमेंट पद्धत',
  totalQty: 'एकूण प्रमाण',
  youSaved: 'तुमची बचत',
  roundOff: 'राउंड ऑफ',
  taxRoundOff: 'कर राउंड ऑफ',
  amountInWords: 'रक्कम अक्षरी',
  taxableAmount: 'करपात्र रक्कम',
  cgst: 'सीजीएसटी',
  sgst: 'एसजीएसटी',
  igst: 'आयजीएसटी',
  itemCode: 'वस्तू कोड',
  received: 'मिळाले',
  partyBalance: 'पार्टीची सध्याची शिल्लक',
  documentTitles: {
    QUOTATION: 'कोटेशन',
    PROFORMA_INVOICE: 'प्रोफॉर्मा बीजक',
    PURCHASE_INVOICE: 'खरेदी बीजक',
    DELIVERY_CHALLAN: 'डिलिव्हरी चलन',
    CREDIT_NOTE: 'क्रेडिट नोट',
    DEBIT_NOTE: 'डेबिट नोट',
  },
  thanks: (business) => `आपल्या व्यवसायाबद्दल धन्यवाद &mdash; ${business}`,
  computerGenerated: (title, business) => `हे ${business} कडून संगणकाद्वारे तयार केलेले ${title} आहे.`,
};

const gujarati: PdfLabels = {
  taxInvoice: 'ટેક્સ ઇનવોઇસ',
  invoice: 'ઇનવોઇસ',
  billedTo: 'બિલ મેળવનાર',
  billTo: 'બિલ મેળવનાર',
  supplier: 'સપ્લાયર',
  issuedBy: 'જારીકર્તા',
  invoiceDate: 'ઇનવોઇસ તારીખ',
  issueDate: 'જારી તારીખ',
  validUntil: 'માન્ય તારીખ સુધી',
  dueDate: 'નિયત તારીખ',
  againstInvoice: 'ઇનવોઇસ સામે',
  reference: 'સંદર્ભ',
  placeOfSupply: 'પુરવઠાનું સ્થળ',
  transport: 'પરિવહન',
  vehicleNumber: 'વાહન નંબર',
  eWayBill: 'ઈ-વે બિલ',
  description: 'વર્ણન',
  qty: 'જથ્થો',
  rate: 'દર',
  unitPrice: 'એકમ કિંમત',
  gst: 'જીએસટી',
  tax: 'કર',
  amount: 'રકમ',
  hsnSac: 'એચએસએન/એસએસી',
  subtotal: 'પેટા-કુલ',
  discount: 'વળતર',
  total: 'કુલ',
  paid: 'ચૂકવેલ',
  balanceDue: 'બાકી રકમ',
  reason: 'કારણ',
  terms: 'નિયમો અને શરતો',
  notes: 'નોંધ',
  gstin: 'જીએસટીઆઈએન',
  tin: 'ટીન',
  nonGst: 'જીએસટી વગરનો વ્યવસાય',
  signatory: 'અધિકૃત હસ્તાક્ષરકર્તા',
  billOfSupply: 'સપ્લાય બિલ',
  compositionNote: 'કમ્પોઝિશન કરદાતા, સપ્લાય પર કર વસૂલવા પાત્ર નથી',
  reverseCharge: 'રિવર્સ ચાર્જ પર ચૂકવવાપાત્ર કર',
  yes: 'હા',
  originalForRecipient: 'પ્રાપ્તકર્તા માટે મૂળ નકલ',
  receivedBy: 'મેળવનાર',
  deliveredBy: 'પહોંચાડનાર',
  acknowledgement: 'ઉપરોક્ત માલ / સેવાઓ સારી સ્થિતિમાં મળી.',
  bankDetails: 'બેંક વિગતો',
  bankName: 'બેંક',
  accountNumber: 'ખાતા નંબર',
  ifsc: 'આઈએફએસસી',
  upiId: 'યુપીઆઈ આઈડી',
  scanToPay: 'ચૂકવવા સ્કેન કરો',
  paymentMode: 'ચુકવણી રીત',
  totalQty: 'કુલ જથ્થો',
  youSaved: 'તમારી બચત',
  roundOff: 'રાઉન્ડ ઓફ',
  taxRoundOff: 'કર રાઉન્ડ ઓફ',
  amountInWords: 'રકમ અક્ષરોમાં',
  taxableAmount: 'કરપાત્ર રકમ',
  cgst: 'સીજીએસટી',
  sgst: 'એસજીએસટી',
  igst: 'આઈજીએસટી',
  itemCode: 'વસ્તુ કોડ',
  received: 'પ્રાપ્ત',
  partyBalance: 'પાર્ટીની વર્તમાન બાકી રકમ',
  documentTitles: {
    QUOTATION: 'ક્વોટેશન',
    PROFORMA_INVOICE: 'પ્રોફોર્મા ઇનવોઇસ',
    PURCHASE_INVOICE: 'ખરીદ ઇનવોઇસ',
    DELIVERY_CHALLAN: 'ડિલિવરી ચલાન',
    CREDIT_NOTE: 'ક્રેડિટ નોટ',
    DEBIT_NOTE: 'ડેબિટ નોટ',
  },
  thanks: (business) => `આપના વ્યવસાય બદલ આભાર &mdash; ${business}`,
  computerGenerated: (title, business) => `આ ${business} દ્વારા કમ્પ્યુટરથી બનાવેલ ${title} છે.`,
};

export const PDF_LABELS: Record<PrintLanguage, PdfLabels> = { english, hindi, marathi, gujarati };
